// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: explore-service-cache.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheService_GetLikedYouCount_FullMethodName           = "/cache.CacheService/GetLikedYouCount"
	CacheService_AppendNewLikeToCache_FullMethodName       = "/cache.CacheService/AppendNewLikeToCache"
	CacheService_RemoveMutualMatchFromCache_FullMethodName = "/cache.CacheService/RemoveMutualMatchFromCache"
	CacheService_ListNewLikedYouFromCache_FullMethodName   = "/cache.CacheService/ListNewLikedYouFromCache"
)

// CacheServiceClient is the client API for CacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CacheService orchestrates the high-speed in-memory database operations
// to offload heavy relational aggregation scans from the core database read-replicas.
type CacheServiceClient interface {
	// GetLikedYouCount fetches the absolute in-memory counter metrics for a specific profile.
	// It handles sentinel evaluations to shield the datastore from cache penetration cascades.
	GetLikedYouCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// AppendNewLikeToCache records an inbound decision into the user's Sorted Set (ZSET)
	// and atomically increments the profile's string metrics counter via a Redis pipeline channel.
	AppendNewLikeToCache(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// RemoveMutualMatchFromCache executes a bidirectional eviction pass across memory pools
	// the split-second a mutual match is achieved, maintaining strict eventual consistency.
	RemoveMutualMatchFromCache(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	ListNewLikedYouFromCache(ctx context.Context, in *CacheListRequest, opts ...grpc.CallOption) (*CacheListResponse, error)
}

type cacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheServiceClient(cc grpc.ClientConnInterface) CacheServiceClient {
	return &cacheServiceClient{cc}
}

func (c *cacheServiceClient) GetLikedYouCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, CacheService_GetLikedYouCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) AppendNewLikeToCache(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, CacheService_AppendNewLikeToCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) RemoveMutualMatchFromCache(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, CacheService_RemoveMutualMatchFromCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) ListNewLikedYouFromCache(ctx context.Context, in *CacheListRequest, opts ...grpc.CallOption) (*CacheListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheListResponse)
	err := c.cc.Invoke(ctx, CacheService_ListNewLikedYouFromCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServiceServer is the server API for CacheService service.
// All implementations must embed UnimplementedCacheServiceServer
// for forward compatibility.
//
// CacheService orchestrates the high-speed in-memory database operations
// to offload heavy relational aggregation scans from the core database read-replicas.
type CacheServiceServer interface {
	// GetLikedYouCount fetches the absolute in-memory counter metrics for a specific profile.
	// It handles sentinel evaluations to shield the datastore from cache penetration cascades.
	GetLikedYouCount(context.Context, *CountRequest) (*CountResponse, error)
	// AppendNewLikeToCache records an inbound decision into the user's Sorted Set (ZSET)
	// and atomically increments the profile's string metrics counter via a Redis pipeline channel.
	AppendNewLikeToCache(context.Context, *AppendRequest) (*EmptyResponse, error)
	// RemoveMutualMatchFromCache executes a bidirectional eviction pass across memory pools
	// the split-second a mutual match is achieved, maintaining strict eventual consistency.
	RemoveMutualMatchFromCache(context.Context, *EvictRequest) (*EmptyResponse, error)
	ListNewLikedYouFromCache(context.Context, *CacheListRequest) (*CacheListResponse, error)
	mustEmbedUnimplementedCacheServiceServer()
}

// UnimplementedCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheServiceServer struct{}

func (UnimplementedCacheServiceServer) GetLikedYouCount(context.Context, *CountRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikedYouCount not implemented")
}
func (UnimplementedCacheServiceServer) AppendNewLikeToCache(context.Context, *AppendRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendNewLikeToCache not implemented")
}
func (UnimplementedCacheServiceServer) RemoveMutualMatchFromCache(context.Context, *EvictRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMutualMatchFromCache not implemented")
}
func (UnimplementedCacheServiceServer) ListNewLikedYouFromCache(context.Context, *CacheListRequest) (*CacheListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNewLikedYouFromCache not implemented")
}
func (UnimplementedCacheServiceServer) mustEmbedUnimplementedCacheServiceServer() {}
func (UnimplementedCacheServiceServer) testEmbeddedByValue()                      {}

// UnsafeCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheServiceServer will
// result in compilation errors.
type UnsafeCacheServiceServer interface {
	mustEmbedUnimplementedCacheServiceServer()
}

func RegisterCacheServiceServer(s grpc.ServiceRegistrar, srv CacheServiceServer) {
	// If the following call panics, it indicates UnimplementedCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheService_ServiceDesc, srv)
}

func _CacheService_GetLikedYouCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).GetLikedYouCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_GetLikedYouCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).GetLikedYouCount(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_AppendNewLikeToCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).AppendNewLikeToCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_AppendNewLikeToCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).AppendNewLikeToCache(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_RemoveMutualMatchFromCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).RemoveMutualMatchFromCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_RemoveMutualMatchFromCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).RemoveMutualMatchFromCache(ctx, req.(*EvictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_ListNewLikedYouFromCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).ListNewLikedYouFromCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_ListNewLikedYouFromCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).ListNewLikedYouFromCache(ctx, req.(*CacheListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheService_ServiceDesc is the grpc.ServiceDesc for CacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLikedYouCount",
			Handler:    _CacheService_GetLikedYouCount_Handler,
		},
		{
			MethodName: "AppendNewLikeToCache",
			Handler:    _CacheService_AppendNewLikeToCache_Handler,
		},
		{
			MethodName: "RemoveMutualMatchFromCache",
			Handler:    _CacheService_RemoveMutualMatchFromCache_Handler,
		},
		{
			MethodName: "ListNewLikedYouFromCache",
			Handler:    _CacheService_ListNewLikedYouFromCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "explore-service-cache.proto",
}
