// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: explore-service-cache.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target user ID whose incoming likes metric is being aggregated.
	RecipientUserId string `protobuf:"bytes,1,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_explore_service_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CountRequest) GetRecipientUserId() string {
	if x != nil {
		return x.RecipientUserId
	}
	return ""
}

type CountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The absolute cached metrics count total.
	Count         uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_explore_service_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AppendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The person who initiated the swiping action (The Inbound Liker).
	ActorUserId string `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	// The recipient profile capturing the like action.
	RecipientUserId string `protobuf:"bytes,2,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	// The liked recipient user
	LikedRecipient bool `protobuf:"varint,3,opt,name=liked_recipient,json=likedRecipient,proto3" json:"liked_recipient,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_explore_service_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *AppendRequest) GetRecipientUserId() string {
	if x != nil {
		return x.RecipientUserId
	}
	return ""
}

func (x *AppendRequest) GetLikedRecipient() bool {
	if x != nil {
		return x.LikedRecipient
	}
	return false
}

type EvictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID components forming the mutual match boundaries.
	// Order independent inside the internal hash lookup layer.
	UserA         string `protobuf:"bytes,1,opt,name=user_a,json=userA,proto3" json:"user_a,omitempty"`
	UserB         string `protobuf:"bytes,2,opt,name=user_b,json=userB,proto3" json:"user_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictRequest) Reset() {
	*x = EvictRequest{}
	mi := &file_explore_service_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictRequest) ProtoMessage() {}

func (x *EvictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictRequest.ProtoReflect.Descriptor instead.
func (*EvictRequest) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{3}
}

func (x *EvictRequest) GetUserA() string {
	if x != nil {
		return x.UserA
	}
	return ""
}

func (x *EvictRequest) GetUserB() string {
	if x != nil {
		return x.UserB
	}
	return ""
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_explore_service_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{4}
}

type CacheListRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecipientUserId string                 `protobuf:"bytes,1,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	PaginationToken *string                `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken,proto3,oneof" json:"pagination_token,omitempty"`
	PageSize        *uint32                `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"` // Amount of items wanted in a single page
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CacheListRequest) Reset() {
	*x = CacheListRequest{}
	mi := &file_explore_service_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheListRequest) ProtoMessage() {}

func (x *CacheListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheListRequest.ProtoReflect.Descriptor instead.
func (*CacheListRequest) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{5}
}

func (x *CacheListRequest) GetRecipientUserId() string {
	if x != nil {
		return x.RecipientUserId
	}
	return ""
}

func (x *CacheListRequest) GetPaginationToken() string {
	if x != nil && x.PaginationToken != nil {
		return *x.PaginationToken
	}
	return ""
}

func (x *CacheListRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type CacheListResponse struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	Likers              []*CacheListResponse_Liker `protobuf:"bytes,1,rep,name=likers,proto3" json:"likers,omitempty"`
	NextPaginationToken *string                    `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3,oneof" json:"next_pagination_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CacheListResponse) Reset() {
	*x = CacheListResponse{}
	mi := &file_explore_service_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheListResponse) ProtoMessage() {}

func (x *CacheListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheListResponse.ProtoReflect.Descriptor instead.
func (*CacheListResponse) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{6}
}

func (x *CacheListResponse) GetLikers() []*CacheListResponse_Liker {
	if x != nil {
		return x.Likers
	}
	return nil
}

func (x *CacheListResponse) GetNextPaginationToken() string {
	if x != nil && x.NextPaginationToken != nil {
		return *x.NextPaginationToken
	}
	return ""
}

type CacheListResponse_Liker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	UnixTimestamp uint64                 `protobuf:"varint,2,opt,name=unix_timestamp,json=unixTimestamp,proto3" json:"unix_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheListResponse_Liker) Reset() {
	*x = CacheListResponse_Liker{}
	mi := &file_explore_service_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheListResponse_Liker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheListResponse_Liker) ProtoMessage() {}

func (x *CacheListResponse_Liker) ProtoReflect() protoreflect.Message {
	mi := &file_explore_service_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheListResponse_Liker.ProtoReflect.Descriptor instead.
func (*CacheListResponse_Liker) Descriptor() ([]byte, []int) {
	return file_explore_service_cache_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CacheListResponse_Liker) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CacheListResponse_Liker) GetUnixTimestamp() uint64 {
	if x != nil {
		return x.UnixTimestamp
	}
	return 0
}

var File_explore_service_cache_proto protoreflect.FileDescriptor

const file_explore_service_cache_proto_rawDesc = "" +
	"\n" +
	"\x1bexplore-service-cache.proto\x12\x05cache\":\n" +
	"\fCountRequest\x12*\n" +
	"\x11recipient_user_id\x18\x01 \x01(\tR\x0frecipientUserId\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\x88\x01\n" +
	"\rAppendRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12*\n" +
	"\x11recipient_user_id\x18\x02 \x01(\tR\x0frecipientUserId\x12'\n" +
	"\x0fliked_recipient\x18\x03 \x01(\bR\x0elikedRecipient\"<\n" +
	"\fEvictRequest\x12\x15\n" +
	"\x06user_a\x18\x01 \x01(\tR\x05userA\x12\x15\n" +
	"\x06user_b\x18\x02 \x01(\tR\x05userB\"\x0f\n" +
	"\rEmptyResponse\"\xb3\x01\n" +
	"\x10CacheListRequest\x12*\n" +
	"\x11recipient_user_id\x18\x01 \x01(\tR\x0frecipientUserId\x12.\n" +
	"\x10pagination_token\x18\x02 \x01(\tH\x00R\x0fpaginationToken\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\rH\x01R\bpageSize\x88\x01\x01B\x13\n" +
	"\x11_pagination_tokenB\f\n" +
	"\n" +
	"_page_size\"\xe9\x01\n" +
	"\x11CacheListResponse\x126\n" +
	"\x06likers\x18\x01 \x03(\v2\x1e.cache.CacheListResponse.LikerR\x06likers\x127\n" +
	"\x15next_pagination_token\x18\x02 \x01(\tH\x00R\x13nextPaginationToken\x88\x01\x01\x1aI\n" +
	"\x05Liker\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12%\n" +
	"\x0eunix_timestamp\x18\x02 \x01(\x04R\runixTimestampB\x18\n" +
	"\x16_next_pagination_token2\xa9\x02\n" +
	"\fCacheService\x12=\n" +
	"\x10GetLikedYouCount\x12\x13.cache.CountRequest\x1a\x14.cache.CountResponse\x12B\n" +
	"\x14AppendNewLikeToCache\x12\x14.cache.AppendRequest\x1a\x14.cache.EmptyResponse\x12G\n" +
	"\x1aRemoveMutualMatchFromCache\x12\x13.cache.EvictRequest\x1a\x14.cache.EmptyResponse\x12M\n" +
	"\x18ListNewLikedYouFromCache\x12\x17.cache.CacheListRequest\x1a\x18.cache.CacheListResponseb\x06proto3"

var (
	file_explore_service_cache_proto_rawDescOnce sync.Once
	file_explore_service_cache_proto_rawDescData []byte
)

func file_explore_service_cache_proto_rawDescGZIP() []byte {
	file_explore_service_cache_proto_rawDescOnce.Do(func() {
		file_explore_service_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_explore_service_cache_proto_rawDesc), len(file_explore_service_cache_proto_rawDesc)))
	})
	return file_explore_service_cache_proto_rawDescData
}

var file_explore_service_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_explore_service_cache_proto_goTypes = []any{
	(*CountRequest)(nil),            // 0: cache.CountRequest
	(*CountResponse)(nil),           // 1: cache.CountResponse
	(*AppendRequest)(nil),           // 2: cache.AppendRequest
	(*EvictRequest)(nil),            // 3: cache.EvictRequest
	(*EmptyResponse)(nil),           // 4: cache.EmptyResponse
	(*CacheListRequest)(nil),        // 5: cache.CacheListRequest
	(*CacheListResponse)(nil),       // 6: cache.CacheListResponse
	(*CacheListResponse_Liker)(nil), // 7: cache.CacheListResponse.Liker
}
var file_explore_service_cache_proto_depIdxs = []int32{
	7, // 0: cache.CacheListResponse.likers:type_name -> cache.CacheListResponse.Liker
	0, // 1: cache.CacheService.GetLikedYouCount:input_type -> cache.CountRequest
	2, // 2: cache.CacheService.AppendNewLikeToCache:input_type -> cache.AppendRequest
	3, // 3: cache.CacheService.RemoveMutualMatchFromCache:input_type -> cache.EvictRequest
	5, // 4: cache.CacheService.ListNewLikedYouFromCache:input_type -> cache.CacheListRequest
	1, // 5: cache.CacheService.GetLikedYouCount:output_type -> cache.CountResponse
	4, // 6: cache.CacheService.AppendNewLikeToCache:output_type -> cache.EmptyResponse
	4, // 7: cache.CacheService.RemoveMutualMatchFromCache:output_type -> cache.EmptyResponse
	6, // 8: cache.CacheService.ListNewLikedYouFromCache:output_type -> cache.CacheListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_explore_service_cache_proto_init() }
func file_explore_service_cache_proto_init() {
	if File_explore_service_cache_proto != nil {
		return
	}
	file_explore_service_cache_proto_msgTypes[5].OneofWrappers = []any{}
	file_explore_service_cache_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_explore_service_cache_proto_rawDesc), len(file_explore_service_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_explore_service_cache_proto_goTypes,
		DependencyIndexes: file_explore_service_cache_proto_depIdxs,
		MessageInfos:      file_explore_service_cache_proto_msgTypes,
	}.Build()
	File_explore_service_cache_proto = out.File
	file_explore_service_cache_proto_goTypes = nil
	file_explore_service_cache_proto_depIdxs = nil
}
